# Adapted from various sources, including:
# - Louis Dionne's Hana: https://github.com/ldionne/hana
# - Paul Fultz II's FIT: https://github.com/pfultz2/Fit
# - Eric Niebler's range-v3: https://github.com/ericniebler/range-v3
# - Gabi Melman spdlog: https://github.com/gabime/spdlog
sudo: required
language: cpp

addons: &gcc48
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test

addons: &gcc7
  apt:
    packages:
      - g++-7
    sources:
      - ubuntu-toolchain-r-test

addons: &clang35
  apt:
    packages:
      - clang-3.5
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5

addons: &clang6
  apt:
    packages:
      - clang-6.0
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0


matrix:
  include:
    # Test gcc-4.8: C++11, Build=Debug/Release
    - env: GCC_VERSION=4.8 CXX_OPTIMIZE=OFF CPP=11
      os: linux
      addons: *gcc48

    - env: GCC_VERSION=7 CXX_OPTIMIZE=OFF CPP=11
      os: linux
      addons: *gcc7

    # Test clang-3.5: C++11, Build=Debug/Release
    - env: CLANG_VERSION=3.5 CXX_OPTIMIZE=OFF CPP=11
      os: linux
      addons: *clang35

      # Test clang-6.0: C++11, CXX_OPTIMIZE=OFF
    - env: CLANG_VERSION=6.0 CXX_OPTIMIZE=OFF CPP=11
      os: linux
      addons: *clang6
      
      # osx
    - env: CXX_OPTIMIZE=OFF CPP=11
      os: osx
    



before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - |
    cmake .. \
      --warn-uninitialized \
      -DBasalt_CXX_OPTIMIZE:BOOL=$CXX_OPTIMIZE \
      -DCMAKE_CXX_STANDARD=$CPP \
  - make VERBOSE=1 -j2
  - ctest -j2 --output-on-failure



notifications:
  email: false