# Adapted from various sources, including:
# - Louis Dionne's Hana: https://github.com/ldionne/hana
# - Paul Fultz II's FIT: https://github.com/pfultz2/Fit
# - Eric Niebler's range-v3: https://github.com/ericniebler/range-v3
# - Gabi Melman spdlog: https://github.com/gabime/spdlog
sudo: false
language: cpp

addons: &gcc7
  apt:
    packages:
    - doxygen
    - g++-7
    - libhdf5-dev
    - librocksdb-dev
    - python3-babel
    - python3-bs4
    - python3-docutils
    - python3-babel
    - python3-h5py
    - python3-lxml
    - python3-numpy
    - python3-pygments
    - python3-pyparsing
    - python3-setuptools
    - python3-wheel
    sources:
    - ubuntu-toolchain-r-test

addons: &clang6
  apt:
    packages:
    - clang-6.0
    - doxygen
    - libhdf5-dev
    - librocksdb-dev
    - python3-babel
    - python3-bs4
    - python3-docutils
    - python3-h5py
    - python3-lxml
    - python3-numpy
    - python3-pygments
    - python3-pyparsing
    - python3-setuptools
    - python3-wheel
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-6.0

addons: &clang7
  apt:
    packages:
    - clang-7
    - libhdf5-dev
    - librocksdb-dev
    - python3-babel
    - python3-bs4
    - python3-docutils
    - python3-h5py
    - python3-lxml
    - python3-numpy
    - python3-pygments
    - python3-pyparsing
    - python3-setuptools
    - python3-wheel
    - valgrind
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-7

addons: &clang8
  apt:
    packages:
    - clang-8
    - doxygen
    - libhdf5-dev
    - librocksdb-dev
    - python3-babel
    - python3-bs4
    - python3-docutils
    - python3-h5py
    - python3-lxml
    - python3-numpy
    - python3-pygments
    - python3-pyparsing
    - python3-setuptools
    - python3-wheel
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-8

matrix:
  allow_failures:
    - os: osx
  include:
      # Test gcc-7: C++11
    - env: GCC_VERSION=7 CXX_OPTIMIZE=OFF CPP=11
      os: linux
      dist: xenial
      addons: *gcc7

      # Test clang-6.0: C++11
    - env: CLANG_VERSION=6.0 CXX_OPTIMIZE=OFF CPP=11
      os: linux
      dist: xenial
      addons: *clang6

      # Test clang-7: C++11
    - env: CPP_CHECK=yes CLANG_VERSION=7 CXX_OPTIMIZE=OFF CPP=11 CTEST_ACTION="-T memcheck"
      os: linux
      dist: xenial
      addons: *clang7

      # Test clang-8: C++11
    - env: CLANG_VERSION=8 CXX_OPTIMIZE=OFF CPP=11
      os: linux
      dist: xenial
      addons: *clang8

      # osx
    - env: CXX_OPTIMIZE=OFF CPP=11
      os: osx
      addons:
        homebrew:
          update: true
          packages:
          - doxygen
          - hdf5
          - llvm
          - numpy
          - rocksdb

before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; ln -s "/usr/local/opt/llvm/bin/clang-tidy" "/usr/local/bin/clang-tidy"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version

script:
  - dev/travis-build

notifications:
  email: false
